# Installed by nvidia-legacy-390xx-kernel-support.
# The NVIDIA and nouveau drivers cannot be loaded at the same time.
blacklist nouveau
blacklist lbm-nouveau
alias nouveau off
options nouveau modeset=0
